package com.posadas.process.beans;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FieldsByPackage implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public FieldsByPackage() {
    }

}