package com.posadas.process.beans;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Messages implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "program")
   private java.lang.String program;
   @org.kie.api.definition.type.Label(value = "locale")
   private java.lang.String locale;
   @org.kie.api.definition.type.Label(value = "field")
   private java.lang.String field;
   @org.kie.api.definition.type.Label(value = "error")
   private java.lang.String error;

   public Messages()
   {
   }

   public java.lang.String getProgram()
   {
      return this.program;
   }

   public void setProgram(java.lang.String program)
   {
      this.program = program;
   }

   public java.lang.String getLocale()
   {
      return this.locale;
   }

   public void setLocale(java.lang.String locale)
   {
      this.locale = locale;
   }

   public java.lang.String getField()
   {
      return this.field;
   }

   public void setField(java.lang.String field)
   {
      this.field = field;
   }

   public java.lang.String getError()
   {
      return this.error;
   }

   public void setError(java.lang.String error)
   {
      this.error = error;
   }

   public Messages(java.lang.String program, java.lang.String locale,
         java.lang.String field, java.lang.String error)
   {
      this.program = program;
      this.locale = locale;
      this.field = field;
      this.error = error;
   }

}