package com.posadas.process.profileupdate;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FieldsByPackage implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "firstName")
   private java.lang.Boolean firstName;
   @org.kie.api.definition.type.Label(value = "middleName")
   private java.lang.Boolean middleName;
   @org.kie.api.definition.type.Label(value = "lastName")
   private java.lang.Boolean lastName;
   @org.kie.api.definition.type.Label(value = "secondLastName")
   private java.lang.Boolean secondLastName;
   @org.kie.api.definition.type.Label(value = "email")
   private java.lang.Boolean email;
   @org.kie.api.definition.type.Label(value = "birthDate")
   private java.lang.Boolean birthDate;
   @org.kie.api.definition.type.Label(value = "country")
   private java.lang.Boolean country;
   @org.kie.api.definition.type.Label(value = "state")
   private java.lang.Boolean state;
   @org.kie.api.definition.type.Label(value = "city")
   private java.lang.Boolean city;
   @org.kie.api.definition.type.Label(value = "colony")
   private java.lang.Boolean colony;
   @org.kie.api.definition.type.Label(value = "addressType")
   private java.lang.Boolean addressType;
   @org.kie.api.definition.type.Label(value = "zipCode")
   private java.lang.Boolean zipCode;
   @org.kie.api.definition.type.Label(value = "streetAddress")
   private java.lang.Boolean streetAddress;
   @org.kie.api.definition.type.Label(value = "interiorNumber")
   private java.lang.Boolean interiorNumber;
   @org.kie.api.definition.type.Label(value = "exteriorNumber")
   private java.lang.Boolean exteriorNumber;
   @org.kie.api.definition.type.Label(value = "phoneNumber")
   private java.lang.Boolean phoneNumber;
   @org.kie.api.definition.type.Label(value = "useType")
   private java.lang.Boolean useType;
   @org.kie.api.definition.type.Label(value = "cardHolder")
   private java.lang.Boolean cardHolder;
   @org.kie.api.definition.type.Label(value = "cardType")
   private java.lang.Boolean cardType;
   @org.kie.api.definition.type.Label(value = "cvvNumber")
   private java.lang.Boolean cvvNumber;
   @org.kie.api.definition.type.Label(value = "package")
   private java.lang.String package_;
   @org.kie.api.definition.type.Label(value = "program")
   private java.lang.String program;
   @org.kie.api.definition.type.Label(value = "interiorNum")
   private java.lang.Boolean interiorNum;
   @org.kie.api.definition.type.Label(value = "externalNum")
   private java.lang.Boolean externalNum;
   @org.kie.api.definition.type.Label(value = "nameCompany")
   private java.lang.Boolean nameCompany;
   @org.kie.api.definition.type.Label(value = "county")
   private java.lang.Boolean county;
   @org.kie.api.definition.type.Label(value = "addresLine1")
   private java.lang.Boolean addresLine1;
   @org.kie.api.definition.type.Label(value = "addresLine2")
   private java.lang.Boolean addresLine2;

   public FieldsByPackage()
   {
   }

   public java.lang.Boolean getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.Boolean firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.Boolean getMiddleName()
   {
      return this.middleName;
   }

   public void setMiddleName(java.lang.Boolean middleName)
   {
      this.middleName = middleName;
   }

   public java.lang.Boolean getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.Boolean lastName)
   {
      this.lastName = lastName;
   }

   public java.lang.Boolean getSecondLastName()
   {
      return this.secondLastName;
   }

   public void setSecondLastName(java.lang.Boolean secondLastName)
   {
      this.secondLastName = secondLastName;
   }

   public java.lang.Boolean getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.Boolean email)
   {
      this.email = email;
   }

   public java.lang.Boolean getBirthDate()
   {
      return this.birthDate;
   }

   public void setBirthDate(java.lang.Boolean birthDate)
   {
      this.birthDate = birthDate;
   }

   public java.lang.Boolean getCountry()
   {
      return this.country;
   }

   public void setCountry(java.lang.Boolean country)
   {
      this.country = country;
   }

   public java.lang.Boolean getState()
   {
      return this.state;
   }

   public void setState(java.lang.Boolean state)
   {
      this.state = state;
   }

   public java.lang.Boolean getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.Boolean city)
   {
      this.city = city;
   }

   public java.lang.Boolean getColony()
   {
      return this.colony;
   }

   public void setColony(java.lang.Boolean colony)
   {
      this.colony = colony;
   }

   public java.lang.Boolean getAddressType()
   {
      return this.addressType;
   }

   public void setAddressType(java.lang.Boolean addressType)
   {
      this.addressType = addressType;
   }

   public java.lang.Boolean getZipCode()
   {
      return this.zipCode;
   }

   public void setZipCode(java.lang.Boolean zipCode)
   {
      this.zipCode = zipCode;
   }

   public java.lang.Boolean getStreetAddress()
   {
      return this.streetAddress;
   }

   public void setStreetAddress(java.lang.Boolean streetAddress)
   {
      this.streetAddress = streetAddress;
   }

   public java.lang.Boolean getInteriorNumber()
   {
      return this.interiorNumber;
   }

   public void setInteriorNumber(java.lang.Boolean interiorNumber)
   {
      this.interiorNumber = interiorNumber;
   }

   public java.lang.Boolean getExteriorNumber()
   {
      return this.exteriorNumber;
   }

   public void setExteriorNumber(java.lang.Boolean exteriorNumber)
   {
      this.exteriorNumber = exteriorNumber;
   }

   public java.lang.Boolean getPhoneNumber()
   {
      return this.phoneNumber;
   }

   public void setPhoneNumber(java.lang.Boolean phoneNumber)
   {
      this.phoneNumber = phoneNumber;
   }

   public java.lang.Boolean getUseType()
   {
      return this.useType;
   }

   public void setUseType(java.lang.Boolean useType)
   {
      this.useType = useType;
   }

   public java.lang.Boolean getCardHolder()
   {
      return this.cardHolder;
   }

   public void setCardHolder(java.lang.Boolean cardHolder)
   {
      this.cardHolder = cardHolder;
   }

   public java.lang.Boolean getCardType()
   {
      return this.cardType;
   }

   public void setCardType(java.lang.Boolean cardType)
   {
      this.cardType = cardType;
   }

   public java.lang.Boolean getCvvNumber()
   {
      return this.cvvNumber;
   }

   public void setCvvNumber(java.lang.Boolean cvvNumber)
   {
      this.cvvNumber = cvvNumber;
   }

   public java.lang.String getPackage_()
   {
      return this.package_;
   }

   public void setPackage_(java.lang.String package_)
   {
      this.package_ = package_;
   }

   public java.lang.String getProgram()
   {
      return this.program;
   }

   public void setProgram(java.lang.String program)
   {
      this.program = program;
   }

   public java.lang.Boolean getInteriorNum()
   {
      return this.interiorNum;
   }

   public void setInteriorNum(java.lang.Boolean interiorNum)
   {
      this.interiorNum = interiorNum;
   }

   public java.lang.Boolean getExternalNum()
   {
      return this.externalNum;
   }

   public void setExternalNum(java.lang.Boolean externalNum)
   {
      this.externalNum = externalNum;
   }

   public java.lang.Boolean getNameCompany()
   {
      return this.nameCompany;
   }

   public void setNameCompany(java.lang.Boolean nameCompany)
   {
      this.nameCompany = nameCompany;
   }

   public java.lang.Boolean getCounty()
   {
      return this.county;
   }

   public void setCounty(java.lang.Boolean county)
   {
      this.county = county;
   }

   public java.lang.Boolean getAddresLine1()
   {
      return this.addresLine1;
   }

   public void setAddresLine1(java.lang.Boolean addresLine1)
   {
      this.addresLine1 = addresLine1;
   }

   public java.lang.Boolean getAddresLine2()
   {
      return this.addresLine2;
   }

   public void setAddresLine2(java.lang.Boolean addresLine2)
   {
      this.addresLine2 = addresLine2;
   }

   public FieldsByPackage(java.lang.Boolean firstName,
         java.lang.Boolean middleName, java.lang.Boolean lastName,
         java.lang.Boolean secondLastName, java.lang.Boolean email,
         java.lang.Boolean birthDate, java.lang.Boolean country,
         java.lang.Boolean state, java.lang.Boolean city,
         java.lang.Boolean colony, java.lang.Boolean addressType,
         java.lang.Boolean zipCode, java.lang.Boolean streetAddress,
         java.lang.Boolean interiorNumber, java.lang.Boolean exteriorNumber,
         java.lang.Boolean phoneNumber, java.lang.Boolean useType,
         java.lang.Boolean cardHolder, java.lang.Boolean cardType,
         java.lang.Boolean cvvNumber, java.lang.String package_,
         java.lang.String program, java.lang.Boolean interiorNum,
         java.lang.Boolean externalNum, java.lang.Boolean nameCompany,
         java.lang.Boolean county, java.lang.Boolean addresLine1,
         java.lang.Boolean addresLine2)
   {
      this.firstName = firstName;
      this.middleName = middleName;
      this.lastName = lastName;
      this.secondLastName = secondLastName;
      this.email = email;
      this.birthDate = birthDate;
      this.country = country;
      this.state = state;
      this.city = city;
      this.colony = colony;
      this.addressType = addressType;
      this.zipCode = zipCode;
      this.streetAddress = streetAddress;
      this.interiorNumber = interiorNumber;
      this.exteriorNumber = exteriorNumber;
      this.phoneNumber = phoneNumber;
      this.useType = useType;
      this.cardHolder = cardHolder;
      this.cardType = cardType;
      this.cvvNumber = cvvNumber;
      this.package_ = package_;
      this.program = program;
      this.interiorNum = interiorNum;
      this.externalNum = externalNum;
      this.nameCompany = nameCompany;
      this.county = county;
      this.addresLine1 = addresLine1;
      this.addresLine2 = addresLine2;
   }

}