package com.posadas.process.profileupdate;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PackagesByProgram implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PackagesByProgram() {
    }

}