package com.posadas.process.profileupdate;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RestrictionsByField implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "required")
   private java.lang.Boolean required;
   @org.kie.api.definition.type.Label(value = "regexp")
   private java.lang.String regexp;
   @org.kie.api.definition.type.Label(value = "program")
   private java.lang.String program;

   public RestrictionsByField()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Boolean getRequired()
   {
      return this.required;
   }

   public void setRequired(java.lang.Boolean required)
   {
      this.required = required;
   }

   public java.lang.String getRegexp()
   {
      return this.regexp;
   }

   public void setRegexp(java.lang.String regexp)
   {
      this.regexp = regexp;
   }

   public java.lang.String getProgram()
   {
      return this.program;
   }

   public void setProgram(java.lang.String program)
   {
      this.program = program;
   }

   public RestrictionsByField(java.lang.String name,
         java.lang.Boolean required, java.lang.String regexp,
         java.lang.String program)
   {
      this.name = name;
      this.required = required;
      this.regexp = regexp;
      this.program = program;
   }

}