package com.posadas.process.statement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FieldsByProgram implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "program")
   private java.lang.String program;
   @org.kie.api.definition.type.Label(value = "package")
   private java.lang.String package_;
   @org.kie.api.definition.type.Label(value = "transactionId")
   private java.lang.Boolean transactionId;
   @org.kie.api.definition.type.Label(value = "processDate")
   private java.lang.Boolean processDate;
   @org.kie.api.definition.type.Label(value = "concept")
   private java.lang.Boolean concept;
   @org.kie.api.definition.type.Label(value = "description")
   private java.lang.Boolean description;
   @org.kie.api.definition.type.Label(value = "comments")
   private java.lang.Boolean comments;
   @org.kie.api.definition.type.Label(value = "value")
   private java.lang.Boolean value;
   @org.kie.api.definition.type.Label(value = "statementNumber")
   private java.lang.Boolean statementNumber;
   @org.kie.api.definition.type.Label(value = "memberName")
   private java.lang.Boolean memberName;
   @org.kie.api.definition.type.Label(value = "currentAvailablePoints")
   private java.lang.Boolean currentAvailablePoints;
   @org.kie.api.definition.type.Label(value = "currentTierName")
   private java.lang.Boolean currentTierName;
   @org.kie.api.definition.type.Label(value = "nextTierName")
   private java.lang.Boolean nextTierName;
   @org.kie.api.definition.type.Label(value = "currentTotalNights")
   private java.lang.Boolean currentTotalNights;
   @org.kie.api.definition.type.Label(value = "checkIn")
   private java.lang.Boolean checkIn;
   @org.kie.api.definition.type.Label(value = "checkOut")
   private java.lang.Boolean checkOut;
   @org.kie.api.definition.type.Label(value = "cveConfirmation")
   private java.lang.Boolean cveConfirmation;
   @org.kie.api.definition.type.Label(value = "hostName")
   private java.lang.Boolean hostName;

   public FieldsByProgram()
   {
   }

   public java.lang.String getProgram()
   {
      return this.program;
   }

   public void setProgram(java.lang.String program)
   {
      this.program = program;
   }

   public java.lang.String getPackage_()
   {
      return this.package_;
   }

   public void setPackage_(java.lang.String package_)
   {
      this.package_ = package_;
   }

   public java.lang.Boolean getTransactionId()
   {
      return this.transactionId;
   }

   public void setTransactionId(java.lang.Boolean transactionId)
   {
      this.transactionId = transactionId;
   }

   public java.lang.Boolean getProcessDate()
   {
      return this.processDate;
   }

   public void setProcessDate(java.lang.Boolean processDate)
   {
      this.processDate = processDate;
   }

   public java.lang.Boolean getConcept()
   {
      return this.concept;
   }

   public void setConcept(java.lang.Boolean concept)
   {
      this.concept = concept;
   }

   public java.lang.Boolean getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.Boolean description)
   {
      this.description = description;
   }

   public java.lang.Boolean getComments()
   {
      return this.comments;
   }

   public void setComments(java.lang.Boolean comments)
   {
      this.comments = comments;
   }

   public java.lang.Boolean getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.Boolean value)
   {
      this.value = value;
   }

   public java.lang.Boolean getStatementNumber()
   {
      return this.statementNumber;
   }

   public void setStatementNumber(java.lang.Boolean statementNumber)
   {
      this.statementNumber = statementNumber;
   }

   public java.lang.Boolean getMemberName()
   {
      return this.memberName;
   }

   public void setMemberName(java.lang.Boolean memberName)
   {
      this.memberName = memberName;
   }

   public java.lang.Boolean getCurrentAvailablePoints()
   {
      return this.currentAvailablePoints;
   }

   public void setCurrentAvailablePoints(
         java.lang.Boolean currentAvailablePoints)
   {
      this.currentAvailablePoints = currentAvailablePoints;
   }

   public java.lang.Boolean getCurrentTierName()
   {
      return this.currentTierName;
   }

   public void setCurrentTierName(java.lang.Boolean currentTierName)
   {
      this.currentTierName = currentTierName;
   }

   public java.lang.Boolean getNextTierName()
   {
      return this.nextTierName;
   }

   public void setNextTierName(java.lang.Boolean nextTierName)
   {
      this.nextTierName = nextTierName;
   }

   public java.lang.Boolean getCurrentTotalNights()
   {
      return this.currentTotalNights;
   }

   public void setCurrentTotalNights(java.lang.Boolean currentTotalNights)
   {
      this.currentTotalNights = currentTotalNights;
   }

   public java.lang.Boolean getCheckIn()
   {
      return this.checkIn;
   }

   public void setCheckIn(java.lang.Boolean checkIn)
   {
      this.checkIn = checkIn;
   }

   public java.lang.Boolean getCheckOut()
   {
      return this.checkOut;
   }

   public void setCheckOut(java.lang.Boolean checkOut)
   {
      this.checkOut = checkOut;
   }

   public java.lang.Boolean getCveConfirmation()
   {
      return this.cveConfirmation;
   }

   public void setCveConfirmation(java.lang.Boolean cveConfirmation)
   {
      this.cveConfirmation = cveConfirmation;
   }

   public java.lang.Boolean getHostName()
   {
      return this.hostName;
   }

   public void setHostName(java.lang.Boolean hostName)
   {
      this.hostName = hostName;
   }

   public FieldsByProgram(java.lang.String program, java.lang.String package_,
         java.lang.Boolean transactionId, java.lang.Boolean processDate,
         java.lang.Boolean concept, java.lang.Boolean description,
         java.lang.Boolean comments, java.lang.Boolean value,
         java.lang.Boolean statementNumber, java.lang.Boolean memberName,
         java.lang.Boolean currentAvailablePoints,
         java.lang.Boolean currentTierName, java.lang.Boolean nextTierName,
         java.lang.Boolean currentTotalNights, java.lang.Boolean checkIn,
         java.lang.Boolean checkOut, java.lang.Boolean cveConfirmation,
         java.lang.Boolean hostName)
   {
      this.program = program;
      this.package_ = package_;
      this.transactionId = transactionId;
      this.processDate = processDate;
      this.concept = concept;
      this.description = description;
      this.comments = comments;
      this.value = value;
      this.statementNumber = statementNumber;
      this.memberName = memberName;
      this.currentAvailablePoints = currentAvailablePoints;
      this.currentTierName = currentTierName;
      this.nextTierName = nextTierName;
      this.currentTotalNights = currentTotalNights;
      this.checkIn = checkIn;
      this.checkOut = checkOut;
      this.cveConfirmation = cveConfirmation;
      this.hostName = hostName;
   }

}