package com.posadas.process.statement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrdersByField implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "field")
   private java.lang.String field;
   @org.kie.api.definition.type.Label(value = "order")
   private java.lang.Integer order;

   public OrdersByField()
   {
   }

   public java.lang.String getField()
   {
      return this.field;
   }

   public void setField(java.lang.String field)
   {
      this.field = field;
   }

   public java.lang.Integer getOrder()
   {
      return this.order;
   }

   public void setOrder(java.lang.Integer order)
   {
      this.order = order;
   }

   public OrdersByField(java.lang.String field, java.lang.Integer order)
   {
      this.field = field;
      this.order = order;
   }

}