package com.posadas.process.statement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrdersByField implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public OrdersByField() {
    }

}