package com.posadas.process.statement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PackagesByProgram implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "program")
   private java.lang.String program;
   @org.kie.api.definition.type.Label(value = "statement")
   private java.lang.Boolean statement;
   @org.kie.api.definition.type.Label(value = "redemptions")
   private java.lang.Boolean redemptions;
   @org.kie.api.definition.type.Label(value = "accruals")
   private java.lang.Boolean accruals;

   public PackagesByProgram()
   {
   }

   public java.lang.String getProgram()
   {
      return this.program;
   }

   public void setProgram(java.lang.String program)
   {
      this.program = program;
   }

   public java.lang.Boolean getStatement()
   {
      return this.statement;
   }

   public void setStatement(java.lang.Boolean statement)
   {
      this.statement = statement;
   }

   public java.lang.Boolean getRedemptions()
   {
      return this.redemptions;
   }

   public void setRedemptions(java.lang.Boolean redemptions)
   {
      this.redemptions = redemptions;
   }

   public java.lang.Boolean getAccruals()
   {
      return this.accruals;
   }

   public void setAccruals(java.lang.Boolean accruals)
   {
      this.accruals = accruals;
   }

   public PackagesByProgram(java.lang.String program,
         java.lang.Boolean statement, java.lang.Boolean redemptions,
         java.lang.Boolean accruals)
   {
      this.program = program;
      this.statement = statement;
      this.redemptions = redemptions;
      this.accruals = accruals;
   }

}