package com.posadas.process.statement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SearchByDateRange implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "program")
   private java.lang.String program;
   @org.kie.api.definition.type.Label(value = "searchByDateRange")
   private java.lang.Boolean searchByDateRange;
   @org.kie.api.definition.type.Label(value = "month1")
   private java.lang.Boolean month1;
   @org.kie.api.definition.type.Label(value = "month2")
   private java.lang.Boolean month2;
   @org.kie.api.definition.type.Label(value = "month3")
   private java.lang.Boolean month3;
   @org.kie.api.definition.type.Label(value = "month6")
   private java.lang.Boolean month6;

   public SearchByDateRange()
   {
   }

   public java.lang.String getProgram()
   {
      return this.program;
   }

   public void setProgram(java.lang.String program)
   {
      this.program = program;
   }

   public java.lang.Boolean getSearchByDateRange()
   {
      return this.searchByDateRange;
   }

   public void setSearchByDateRange(java.lang.Boolean searchByDateRange)
   {
      this.searchByDateRange = searchByDateRange;
   }

   public java.lang.Boolean getMonth1()
   {
      return this.month1;
   }

   public void setMonth1(java.lang.Boolean month1)
   {
      this.month1 = month1;
   }

   public java.lang.Boolean getMonth2()
   {
      return this.month2;
   }

   public void setMonth2(java.lang.Boolean month2)
   {
      this.month2 = month2;
   }

   public java.lang.Boolean getMonth3()
   {
      return this.month3;
   }

   public void setMonth3(java.lang.Boolean month3)
   {
      this.month3 = month3;
   }

   public java.lang.Boolean getMonth6()
   {
      return this.month6;
   }

   public void setMonth6(java.lang.Boolean month6)
   {
      this.month6 = month6;
   }

   public SearchByDateRange(java.lang.String program,
         java.lang.Boolean searchByDateRange, java.lang.Boolean month1,
         java.lang.Boolean month2, java.lang.Boolean month3,
         java.lang.Boolean month6)
   {
      this.program = program;
      this.searchByDateRange = searchByDateRange;
      this.month1 = month1;
      this.month2 = month2;
      this.month3 = month3;
      this.month6 = month6;
   }

}