package com.posadas.process.catalog;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CategoriesByProgram implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "program")
   private java.lang.String program;
   @org.kie.api.definition.type.Label(value = "locale")
   private java.lang.String locale;
   private java.lang.String idCategory01;
   @org.kie.api.definition.type.Label(value = "idCategory02")
   private java.lang.String idCategory02;
   @org.kie.api.definition.type.Label(value = "idCategory03")
   private java.lang.String idCategory03;
   @org.kie.api.definition.type.Label(value = "idCategory04")
   private java.lang.String idCategory04;
   @org.kie.api.definition.type.Label(value = "idCategory05")
   private java.lang.String idCategory05;
   @org.kie.api.definition.type.Label(value = "idCategory06")
   private java.lang.String idCategory06;
   @org.kie.api.definition.type.Label(value = "idCategory07")
   private java.lang.String idCategory07;
   @org.kie.api.definition.type.Label(value = "idCategory08")
   private java.lang.String idCategory08;
   @org.kie.api.definition.type.Label(value = "idCategory09")
   private java.lang.String idCategory09;
   @org.kie.api.definition.type.Label(value = "idCategory10")
   private java.lang.String idCategory10;
   @org.kie.api.definition.type.Label(value = "idCategory11")
   private java.lang.String idCategory11;
   @org.kie.api.definition.type.Label(value = "idCategory12")
   private java.lang.String idCategory12;
   @org.kie.api.definition.type.Label(value = "idCategory13")
   private java.lang.String idCategory13;
   @org.kie.api.definition.type.Label(value = "idCategory14")
   private java.lang.String idCategory14;

   public CategoriesByProgram()
   {
   }

   public java.lang.String getProgram()
   {
      return this.program;
   }

   public void setProgram(java.lang.String program)
   {
      this.program = program;
   }

   public java.lang.String getLocale()
   {
      return this.locale;
   }

   public void setLocale(java.lang.String locale)
   {
      this.locale = locale;
   }

   public java.lang.String getIdCategory01()
   {
      return this.idCategory01;
   }

   public void setIdCategory01(java.lang.String idCategory01)
   {
      this.idCategory01 = idCategory01;
   }

   public java.lang.String getIdCategory02()
   {
      return this.idCategory02;
   }

   public void setIdCategory02(java.lang.String idCategory02)
   {
      this.idCategory02 = idCategory02;
   }

   public java.lang.String getIdCategory03()
   {
      return this.idCategory03;
   }

   public void setIdCategory03(java.lang.String idCategory03)
   {
      this.idCategory03 = idCategory03;
   }

   public java.lang.String getIdCategory04()
   {
      return this.idCategory04;
   }

   public void setIdCategory04(java.lang.String idCategory04)
   {
      this.idCategory04 = idCategory04;
   }

   public java.lang.String getIdCategory05()
   {
      return this.idCategory05;
   }

   public void setIdCategory05(java.lang.String idCategory05)
   {
      this.idCategory05 = idCategory05;
   }

   public java.lang.String getIdCategory06()
   {
      return this.idCategory06;
   }

   public void setIdCategory06(java.lang.String idCategory06)
   {
      this.idCategory06 = idCategory06;
   }

   public java.lang.String getIdCategory07()
   {
      return this.idCategory07;
   }

   public void setIdCategory07(java.lang.String idCategory07)
   {
      this.idCategory07 = idCategory07;
   }

   public java.lang.String getIdCategory08()
   {
      return this.idCategory08;
   }

   public void setIdCategory08(java.lang.String idCategory08)
   {
      this.idCategory08 = idCategory08;
   }

   public java.lang.String getIdCategory09()
   {
      return this.idCategory09;
   }

   public void setIdCategory09(java.lang.String idCategory09)
   {
      this.idCategory09 = idCategory09;
   }

   public java.lang.String getIdCategory10()
   {
      return this.idCategory10;
   }

   public void setIdCategory10(java.lang.String idCategory10)
   {
      this.idCategory10 = idCategory10;
   }

   public java.lang.String getIdCategory11()
   {
      return this.idCategory11;
   }

   public void setIdCategory11(java.lang.String idCategory11)
   {
      this.idCategory11 = idCategory11;
   }

   public java.lang.String getIdCategory12()
   {
      return this.idCategory12;
   }

   public void setIdCategory12(java.lang.String idCategory12)
   {
      this.idCategory12 = idCategory12;
   }

   public java.lang.String getIdCategory13()
   {
      return this.idCategory13;
   }

   public void setIdCategory13(java.lang.String idCategory13)
   {
      this.idCategory13 = idCategory13;
   }

   public java.lang.String getIdCategory14()
   {
      return this.idCategory14;
   }

   public void setIdCategory14(java.lang.String idCategory14)
   {
      this.idCategory14 = idCategory14;
   }

   public CategoriesByProgram(java.lang.String program,
         java.lang.String locale, java.lang.String idCategory01,
         java.lang.String idCategory02, java.lang.String idCategory03,
         java.lang.String idCategory04, java.lang.String idCategory05,
         java.lang.String idCategory06, java.lang.String idCategory07,
         java.lang.String idCategory08, java.lang.String idCategory09,
         java.lang.String idCategory10, java.lang.String idCategory11,
         java.lang.String idCategory12, java.lang.String idCategory13,
         java.lang.String idCategory14)
   {
      this.program = program;
      this.locale = locale;
      this.idCategory01 = idCategory01;
      this.idCategory02 = idCategory02;
      this.idCategory03 = idCategory03;
      this.idCategory04 = idCategory04;
      this.idCategory05 = idCategory05;
      this.idCategory06 = idCategory06;
      this.idCategory07 = idCategory07;
      this.idCategory08 = idCategory08;
      this.idCategory09 = idCategory09;
      this.idCategory10 = idCategory10;
      this.idCategory11 = idCategory11;
      this.idCategory12 = idCategory12;
      this.idCategory13 = idCategory13;
      this.idCategory14 = idCategory14;
   }

}