package com.posadas.process.catalog;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CategoriesByProgram implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CategoriesByProgram() {
    }

}