package com.posadas.process.catalog;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SubCategoryDescription implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "id")
   private java.lang.String id;
   @org.kie.api.definition.type.Label(value = "name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "image")
   private java.lang.String image;

   public SubCategoryDescription()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getImage()
   {
      return this.image;
   }

   public void setImage(java.lang.String image)
   {
      this.image = image;
   }

   public SubCategoryDescription(java.lang.String id, java.lang.String name,
         java.lang.String image)
   {
      this.id = id;
      this.name = name;
      this.image = image;
   }

}